# Generated by Django 2.2 on 2020-04-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200421_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idUser',
            field=models.IntegerField(db_index=True, default=4, primary_key=True, serialize=False),
        ),
    ]
